apiVersion: v1
kind: Pod
metadata:
  name: apache-uat-pod
  labels:
    app: apache-uat
spec:
  nodeSelector:
    role: uat
  containers:
  - name: apache
    image: nirmal46789/alpine-kubepractice-app:uat
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-qatest-pod
  labels:
    app: apache-qatest
spec:
  nodeSelector:
    role: qatest
  containers:
  - name: apache
    image: nirmal46789/alpine-kubepractice-app:qatest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: apache-prod-pod
  labels:
    app: apache-production
spec:
  nodeSelector:
    role: production
  containers:
  - name: apache
    image: nirmal46789/alpine-kubepractice-app:prod
    ports:
    - containerPort: 80
